project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    toc-title: Contents
    toc-location: right
    linkcolor: "green"
    theme: 
      - zephyr
      - custom.scss

website:
  navbar:
    search: true
    title: lighthouse_ice
    background: "primary"
    left:
      - href: index.qmd
        text: Home
      - href: _notebooks/full_report.ipynb
        text: "📊 Full Report"
      - text: "Notebooks"
        menu:
          - href: _notebooks/0.0-collect-data.ipynb
            text: "Data Collection"
          - href: _notebooks/1.0-process-data.ipynb
            text: "Data Processing"
          - href: _notebooks/2.0-analyze-data.ipynb
            text: "Data Analysis"
          - href: _notebooks/3.0-visualize-data.ipynb
            text: "Data Visualization"
          - href: _notebooks/4.0-narrative-report.ipynb
            text: "Narrative Report"
          - href: _notebooks/full_report.ipynb
            text: "Full Report"


execute:
  freeze: auto  # Prevents re-execution of notebooks on every render